{% set name = "pyhdx" %}
{% set version = "0.4.0b3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyHDX-{{ version }}.tar.gz
  sha256: 492ecfc9452d766e7e688334c3f71ed02ae0367ff9567fbc8faa8affef6f7291

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - hdxrate >=0.2.0
    - numpy
    - matplotlib-base
    - pandas
    - scikit-image
    - scipy
    - symfit
    - pytorch
    - tqdm
    - dask
    - distributed
    - packaging

test:
  imports:
    - pyhdx
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: pyhdx-base

#  - name: pyhdx
#    requirements:
#      run:
#       - panel>=0.11.0
#       - bokeh
#       - param
#       - lumen==0.3.0
#       - holoviews
#       - colorcet
#       - hvplot
#       - pylatex
#       - proplot==0.6.4
#    test:
#      imports:
#        - pyhdx

about:
  home: https://github.com/Jhsmit/PyHDX
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Derive Î”G for single residues from HDX-MS data
  doc_url: https://pyhdx.readthedocs.io/
  dev_url: https://github.com/Jhsmit/PyHDX

extra:
  recipe-maintainers:
    - Jhsmit
