{% set name = "pyhdx" %}
{% set version = "0.4.0b5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyHDX-{{ version }}.tar.gz
  sha256: 022b98a7e32c0aea5e93d4e4414b6c27d714d7c63b7f345fdb83c9fb1c8bac0e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - hdxrate >=0.2.0
    - numpy
    - matplotlib-base
    - pandas
    - scikit-image
    - scipy
    - symfit
    - pytorch
    - tqdm
    - dask
    - distributed
    - packaging
test:
  imports:
    - pyhdx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Jhsmit/PyHDX
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Derive Î”G for single residues from HDX-MS data
  doc_url: https://pyhdx.readthedocs.io/
  dev_url: https://github.com/Jhsmit/PyHDX

extra:
  recipe-maintainers:
    - Jhsmit
